# Generated by Django 2.0.2 on 2018-02-20 22:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_num', models.PositiveIntegerField(db_column='id', help_text='A unique ID. Starts counting at one and is just incremented with every post.', primary_key=True, serialize=False)),
                ('tags', models.TextField(blank=True, help_text='Separated by single spaces. Can contain parenthesis, underscores, and probably other special characters.')),
                ('score', models.PositiveIntegerField(help_text="The score given to this post by users voting on it and favoriting it. A 'good' is +1, 'great' is +2, and favoriting is +3. Probably can't be negative.")),
                ('rating', models.CharField(choices=[('s', 'safe'), ('q', 'questionable'), ('e', 'explicit')], help_text="HypnoHub returns it as 's', 'q', or 'e' so that's how we store it.", max_length=1, validators=[django.core.validators.RegexValidator(code='invalid_rating', regex='^[sqe]$')], verbose_name='content rating')),
                ('author', models.CharField(max_length=32)),
                ('md5', models.CharField(help_text="md5 hash of the full-sized(?) image. Used in the URL's for the full-sized, preview, and sample images.", max_length=32, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_md5', regex='^[0-9a-fA-F]{32}$')])),
                ('status', models.CharField(help_text="I have no idea what this field does but it always seems to be either 'active' or 'deleted'.", max_length=32)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vote', serialize=False, to='main_app.Post')),
                ('vote_type', models.PositiveSmallIntegerField(choices=[(1, 'upvote'), (0, 'meh'), (-1, 'downvote')])),
            ],
        ),
    ]
