# Generated by Django 2.0.2 on 2018-02-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='height',
        ),
        migrations.RemoveField(
            model_name='post',
            name='md5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='width',
        ),
        migrations.AddField(
            model_name='post',
            name='file_url',
            field=models.CharField(default='YOU SHOULD NEVER SEE THIS TEXT', help_text='This is the "view larger version" image. Can have seemingly any extension. For images with no "view larger version", this is the main image.', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='jpeg_url',
            field=models.CharField(blank=True, help_text="I'm pretty sure this is file_url but converted to jpg, if necessary.", max_length=64),
        ),
        migrations.AddField(
            model_name='post',
            name='preview_url',
            field=models.CharField(default='YOU SHOULD NEVER SEE THIS TEXT EITHER', help_text="This is what you see when you're looking at multiple images on the same page.", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='sample_url',
            field=models.CharField(blank=True, help_text='This is what you see when you\'re on a page with a "view larger version". file_url is the larger version. On pages with no "view larger version", then you\'re shown the file_url instead.', max_length=64),
        ),
    ]
