# Generated by Django 2.0.2 on 2018-03-03 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180220_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='jpeg_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='main_app.Post'),
        ),
    ]
